#FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04
#FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM nvidia/cuda:12.0.0-cudnn8-runtime-ubuntu22.04
#FROM ubuntu:22.04
MAINTAINER wangrongxiang

ENV TZ=Asia/Shanghai
RUN apt-get -y update && \
    apt-get install -y --no-install-recommends tzdata golang vim && \
    apt-get install -y --no-install-recommends curl sudo git build-essential cmake && \
    apt-get install -y --no-install-recommends libjsoncpp-dev uuid-dev ca-certificates && \
    apt-get install -y --no-install-recommends g++ libssl-dev zlib1g-dev libpq-dev libmysqlclient-dev && \
    apt-get install -y --no-install-recommends nvidia-cuda-toolkit && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*
RUN git config --global http.sslverify false && \
    git config --global https.sslverify false && \
    git clone --recurse https://github.com/janhq/nitro

WORKDIR nitro
RUN ./install_deps.sh

RUN mkdir build
WORKDIR build
RUN cmake -DLLAMA_CUBLAS=ON ..
RUN make -j $(nproc)
WORKDIR /

COPY . ./
RUN mkdir model
RUN go build -o mynitro

ENV GGML_METAL_PATH_RESOURCES="/usr/local/bin"

EXPOSE 3928
EXPOSE 3900

RUN chmod +x docker3.sh
ENTRYPOINT ["./docker3.sh"]
