FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04
MAINTAINER wangrongxiang

ENV TZ=Asia/Shanghai
RUN apt-get -y update && \
    apt-get install -y --no-install-recommends tzdata && \
    apt-get install -y --no-install-recommends yarn curl sudo git make nodejs npm
RUN git config --global http.sslverify false && \
    git config --global https.sslverify false && \
    git clone --recurse https://github.com/janhq/jan
WORKDIR jan
RUN git checkout -b DESIRED_BRANCH

EXPOSE 1337
ENTRYPOINT ["make dev"]