# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Nitro image

on:
  workflow_dispatch:
#  push:
#    branches:
#      - dev_wrx
#  release:
#    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }} # ${{ secrets.DOCKER_PASSWORD }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          # images: ${{ secrets.DOCKER_USERNAME }}/seahub_pgserver
#          images: aboveos/nitro

      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest

      - name: Build Docker image
        # run: docker build --platform linux/amd64 -t aboveos/llama_cpp:${{ steps.get-latest-tag.outputs.tag }} -f ./Dockerfile_llama_cpp .
        run: docker build -t aboveos/llama_cpp:${{ steps.get-latest-tag.outputs.tag }} -f ./Dockerfile_llama_cpp .

      - name: Push Docker image
        run: docker push aboveos/llama_cpp:${{ steps.get-latest-tag.outputs.tag }}

#      - name: Build and push Docker image
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#        with:
#          context: --platform linux/amd64 .
#          file: ./Dockerfile_nitro
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}