# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Nitro image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev_wrx
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
#      - name: Maximize build space
#        uses: easimon/maximize-build-space@master
#        with:
#          root-reserve-mb: 21200
#          swap-size-mb: 1024
#          remove-dotnet: 'true'
#          remove-android: 'true'
#          remove-haskell: 'true'
#          remove-codeql: 'true'

      - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false

          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Clean up disk space
        if: runner.os == 'Linux'
        run: |
          sudo apt-get clean
          sudo rm -rf /tmp/*
          sudo df -h

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }} # ${{ secrets.DOCKER_PASSWORD }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          # images: ${{ secrets.DOCKER_USERNAME }}/seahub_pgserver
#          images: aboveos/nitro

      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest

#      - name: Build Docker image
##        run: docker build --platform linux/amd64 -t aboveos/nitro:${{ steps.get-latest-tag.outputs.tag }} -f ./Dockerfile_nitro .
#        run: docker build -t beclab/nitro:${{ steps.get-latest-tag.outputs.tag }} -f ./Dockerfile_nitro .
#
#      - name: Push Docker image
#        run: docker push beclab/nitro:${{ steps.get-latest-tag.outputs.tag }}

#      - name: Build and push Docker image
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#        with:
#          context: --platform linux/amd64 .
#          file: ./Dockerfile_nitro
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: beclab/nitro:${{ steps.get-latest-tag.outputs.tag }}
          file: ./Dockerfile_nitro
          platforms: linux/amd64,linux/arm64
